/-
Copyright (c) 2026 Travis Darshan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Travis Darshan
-/

import YMFormalization.SU2.PlaquetteLaplacian
import Mathlib

/-!
# Pauli Matrices and the Twisted SU(2) Background

This file connects the coordinate model used in the certified
twisted-cell complex to the actual Pauli-matrix background

`Γ₁ = i σ₁`,
`Γ₂ = i σ₂`,
`Γ₃ = i σ₃`,
`Γ₄ = I`.

A real vector `η : Vec3` represents the Lie-algebra matrix

`i η · σ`.

Conjugation by the twist-eaters is proved to induce the exact
coordinate rotations

`R₁ = diag(1,-1,-1)`,
`R₂ = diag(-1,1,-1)`,
`R₃ = diag(-1,-1,1)`,
`R₄ = I`.
-/

set_option autoImplicit false

namespace YMFormalization
namespace SU2

abbrev Mat2C := Matrix (Fin 2) (Fin 2) ℂ

/-!
## Exact 2x2 multiplication interface

Using explicit entry lemmas avoids leaving nested matrix products
opaque during simplification.
-/

@[simp]
theorem mat2_mul_00 (A B : Mat2C) :
    (A * B) 0 0 = A 0 0 * B 0 0 + A 0 1 * B 1 0 :=
  (Matrix.two_mul_expl A B).1

@[simp]
theorem mat2_mul_01 (A B : Mat2C) :
    (A * B) 0 1 = A 0 0 * B 0 1 + A 0 1 * B 1 1 :=
  (Matrix.two_mul_expl A B).2.1

@[simp]
theorem mat2_mul_10 (A B : Mat2C) :
    (A * B) 1 0 = A 1 0 * B 0 0 + A 1 1 * B 1 0 :=
  (Matrix.two_mul_expl A B).2.2.1

@[simp]
theorem mat2_mul_11 (A B : Mat2C) :
    (A * B) 1 1 = A 1 0 * B 0 1 + A 1 1 * B 1 1 :=
  (Matrix.two_mul_expl A B).2.2.2

/-!
## Explicit entries of a triple 2x2 product

These lemmas expand `(A * B) * C` one entry at a time without
globally rewriting matrix application syntax.
-/

theorem mat2_triple_00 (A B C : Mat2C) :
    (A * B * C) 0 0 =
      (A 0 0 * B 0 0 + A 0 1 * B 1 0) * C 0 0 +
      (A 0 0 * B 0 1 + A 0 1 * B 1 1) * C 1 0 := by
  rw [mat2_mul_00, mat2_mul_00, mat2_mul_01]

theorem mat2_triple_01 (A B C : Mat2C) :
    (A * B * C) 0 1 =
      (A 0 0 * B 0 0 + A 0 1 * B 1 0) * C 0 1 +
      (A 0 0 * B 0 1 + A 0 1 * B 1 1) * C 1 1 := by
  rw [mat2_mul_01, mat2_mul_00, mat2_mul_01]

theorem mat2_triple_10 (A B C : Mat2C) :
    (A * B * C) 1 0 =
      (A 1 0 * B 0 0 + A 1 1 * B 1 0) * C 0 0 +
      (A 1 0 * B 0 1 + A 1 1 * B 1 1) * C 1 0 := by
  rw [mat2_mul_10, mat2_mul_10, mat2_mul_11]

theorem mat2_triple_11 (A B C : Mat2C) :
    (A * B * C) 1 1 =
      (A 1 0 * B 0 0 + A 1 1 * B 1 0) * C 0 1 +
      (A 1 0 * B 0 1 + A 1 1 * B 1 1) * C 1 1 := by
  rw [mat2_mul_11, mat2_mul_10, mat2_mul_11]


/-!
## Scalar complex core for Pauli conjugation

`ring` treats `Complex.I` as a generic ring element.  The special
relation `I * I = -1` is supplied once here and then reused in the
exact shapes generated by the matrix calculations.
-/

theorem I_mul_mul_I (z : ℂ) :
    Complex.I * z * Complex.I = -z := by
  calc
    Complex.I * z * Complex.I
        = z * (Complex.I * Complex.I) := by ring
    _ = z * (-1) := by rw [Complex.I_mul_I]
    _ = -z := by ring

theorem I_mul_mul_negI (z : ℂ) :
    Complex.I * z * (-Complex.I) = z := by
  calc
    Complex.I * z * (-Complex.I)
        = -(Complex.I * z * Complex.I) := by ring
    _ = -(-z) := by rw [I_mul_mul_I]
    _ = z := by ring

theorem negI_mul_mul_I (z : ℂ) :
    (-Complex.I) * z * Complex.I = z := by
  calc
    (-Complex.I) * z * Complex.I
        = -(Complex.I * z * Complex.I) := by ring
    _ = -(-z) := by rw [I_mul_mul_I]
    _ = z := by ring

theorem negI_mul_mul_negI (z : ℂ) :
    (-Complex.I) * z * (-Complex.I) = -z := by
  calc
    (-Complex.I) * z * (-Complex.I)
        = Complex.I * z * Complex.I := by ring
    _ = -z := I_mul_mul_I z

/-- First Pauli matrix. -/
def sigma1 : Mat2C :=
  ![![0, 1],
    ![1, 0]]

/-- Second Pauli matrix. -/
def sigma2 : Mat2C :=
  ![![0, -Complex.I],
    ![Complex.I, 0]]

/-- Third Pauli matrix. -/
def sigma3 : Mat2C :=
  ![![1, 0],
    ![0, -1]]

/-- `Γ₁ = i σ₁`. -/
def gamma1 : Mat2C :=
  ![![0, Complex.I],
    ![Complex.I, 0]]

/-- `Γ₂ = i σ₂`. -/
def gamma2 : Mat2C :=
  ![![0, 1],
    ![-1, 0]]

/-- `Γ₃ = i σ₃`. -/
def gamma3 : Mat2C :=
  ![![Complex.I, 0],
    ![0, -Complex.I]]

/-- `Γ₄ = I`. -/
def gamma4 : Mat2C :=
  ![![1, 0],
    ![0, 1]]

/-- Explicit inverse of `Γ₁`. -/
def gamma1Inv : Mat2C :=
  ![![0, -Complex.I],
    ![-Complex.I, 0]]

/-- Explicit inverse of `Γ₂`. -/
def gamma2Inv : Mat2C :=
  ![![0, -1],
    ![1, 0]]

/-- Explicit inverse of `Γ₃`. -/
def gamma3Inv : Mat2C :=
  ![![-Complex.I, 0],
    ![0, Complex.I]]

/-- Explicit inverse of `Γ₄`. -/
def gamma4Inv : Mat2C := gamma4

/--
Matrix realization of

`η ↦ i η · σ`.
-/
def su2OfVec (η : Vec3) : Mat2C :=
  ![
    ![
      ((η 2 : ℝ) : ℂ) * Complex.I,
      ((η 1 : ℝ) : ℂ) + ((η 0 : ℝ) : ℂ) * Complex.I
    ],
    ![
      -((η 1 : ℝ) : ℂ) + ((η 0 : ℝ) : ℂ) * Complex.I,
      -((η 2 : ℝ) : ℂ) * Complex.I
    ]
  ]

/-- Rotation induced by `Γ₁`. -/
def R1 (η : Vec3) : Vec3 :=
  ![η 0, -η 1, -η 2]

/-- Rotation induced by `Γ₂`. -/
def R2 (η : Vec3) : Vec3 :=
  ![-η 0, η 1, -η 2]

/-- Rotation induced by `Γ₃`. -/
def R3 (η : Vec3) : Vec3 :=
  ![-η 0, -η 1, η 2]

/-- Rotation induced by `Γ₄ = I`. -/
def R4 (η : Vec3) : Vec3 := η

/-!
## Pauli-to-twist identities
-/

theorem gamma1_eq_I_smul_sigma1 :
    gamma1 = Complex.I • sigma1 := by
  ext i j
  rw [Matrix.smul_apply]
  change gamma1 i j = Complex.I * sigma1 i j
  fin_cases i <;>
    fin_cases j <;>
    simp [gamma1, sigma1, Complex.I_mul_I]

theorem gamma2_eq_I_smul_sigma2 :
    gamma2 = Complex.I • sigma2 := by
  ext i j
  rw [Matrix.smul_apply]
  change gamma2 i j = Complex.I * sigma2 i j
  fin_cases i <;>
    fin_cases j <;>
    simp [gamma2, sigma2, Complex.I_mul_I]

theorem gamma3_eq_I_smul_sigma3 :
    gamma3 = Complex.I • sigma3 := by
  ext i j
  rw [Matrix.smul_apply]
  change gamma3 i j = Complex.I * sigma3 i j
  fin_cases i <;>
    fin_cases j <;>
    simp [gamma3, sigma3, Complex.I_mul_I]

/-!
## Exact inverse checks
-/

theorem gamma1_mul_gamma1Inv :
    gamma1 * gamma1Inv = 1 := by
  funext i j
  fin_cases i <;> fin_cases j
  · change (gamma1 * gamma1Inv) 0 0 = (1 : Mat2C) 0 0
    rw [mat2_mul_00]
    simp [gamma1, gamma1Inv, Complex.I_mul_I]
  · change (gamma1 * gamma1Inv) 0 1 = (1 : Mat2C) 0 1
    rw [mat2_mul_01]
    simp [gamma1, gamma1Inv]
  · change (gamma1 * gamma1Inv) 1 0 = (1 : Mat2C) 1 0
    rw [mat2_mul_10]
    simp [gamma1, gamma1Inv]
  · change (gamma1 * gamma1Inv) 1 1 = (1 : Mat2C) 1 1
    rw [mat2_mul_11]
    simp [gamma1, gamma1Inv, Complex.I_mul_I]

theorem gamma2_mul_gamma2Inv :
    gamma2 * gamma2Inv = 1 := by
  funext i j
  fin_cases i <;> fin_cases j
  · change (gamma2 * gamma2Inv) 0 0 = (1 : Mat2C) 0 0
    rw [mat2_mul_00]
    simp [gamma2, gamma2Inv]
  · change (gamma2 * gamma2Inv) 0 1 = (1 : Mat2C) 0 1
    rw [mat2_mul_01]
    simp [gamma2, gamma2Inv]
  · change (gamma2 * gamma2Inv) 1 0 = (1 : Mat2C) 1 0
    rw [mat2_mul_10]
    simp [gamma2, gamma2Inv]
  · change (gamma2 * gamma2Inv) 1 1 = (1 : Mat2C) 1 1
    rw [mat2_mul_11]
    simp [gamma2, gamma2Inv]

theorem gamma3_mul_gamma3Inv :
    gamma3 * gamma3Inv = 1 := by
  funext i j
  fin_cases i <;> fin_cases j
  · change (gamma3 * gamma3Inv) 0 0 = (1 : Mat2C) 0 0
    rw [mat2_mul_00]
    simp [gamma3, gamma3Inv, Complex.I_mul_I]
  · change (gamma3 * gamma3Inv) 0 1 = (1 : Mat2C) 0 1
    rw [mat2_mul_01]
    simp [gamma3, gamma3Inv]
  · change (gamma3 * gamma3Inv) 1 0 = (1 : Mat2C) 1 0
    rw [mat2_mul_10]
    simp [gamma3, gamma3Inv]
  · change (gamma3 * gamma3Inv) 1 1 = (1 : Mat2C) 1 1
    rw [mat2_mul_11]
    simp [gamma3, gamma3Inv, Complex.I_mul_I]

theorem gamma4_mul_gamma4Inv :
    gamma4 * gamma4Inv = 1 := by
  funext i j
  fin_cases i <;> fin_cases j
  · change (gamma4 * gamma4Inv) 0 0 = (1 : Mat2C) 0 0
    rw [mat2_mul_00]
    simp [gamma4, gamma4Inv]
  · change (gamma4 * gamma4Inv) 0 1 = (1 : Mat2C) 0 1
    rw [mat2_mul_01]
    simp [gamma4, gamma4Inv]
  · change (gamma4 * gamma4Inv) 1 0 = (1 : Mat2C) 1 0
    rw [mat2_mul_10]
    simp [gamma4, gamma4Inv]
  · change (gamma4 * gamma4Inv) 1 1 = (1 : Mat2C) 1 1
    rw [mat2_mul_11]
    simp [gamma4, gamma4Inv]

/-!
## Conjugation action
-/

theorem gamma1_conj_su2 (η : Vec3) :
    gamma1 * su2OfVec η * gamma1Inv =
      su2OfVec (R1 η) := by
  funext i j
  fin_cases i <;> fin_cases j
  · change (gamma1 * su2OfVec η * gamma1Inv) 0 0 =
      su2OfVec (R1 η) 0 0
    rw [mat2_triple_00]
    simp [gamma1, gamma1Inv, su2OfVec, R1]
    rw [I_mul_mul_I]
  · change (gamma1 * su2OfVec η * gamma1Inv) 0 1 =
      su2OfVec (R1 η) 0 1
    rw [mat2_triple_01]
    simp [gamma1, gamma1Inv, su2OfVec, R1]
    rw [I_mul_mul_I]
    ring
  · change (gamma1 * su2OfVec η * gamma1Inv) 1 0 =
      su2OfVec (R1 η) 1 0
    rw [mat2_triple_10]
    simp [gamma1, gamma1Inv, su2OfVec, R1]
    rw [I_mul_mul_I]
    ring
  · change (gamma1 * su2OfVec η * gamma1Inv) 1 1 =
      su2OfVec (R1 η) 1 1
    rw [mat2_triple_11]
    simp [gamma1, gamma1Inv, su2OfVec, R1]
    rw [I_mul_mul_I]
    ring

theorem gamma2_conj_su2 (η : Vec3) :
    gamma2 * su2OfVec η * gamma2Inv =
      su2OfVec (R2 η) := by
  funext i j
  fin_cases i <;> fin_cases j
  · change (gamma2 * su2OfVec η * gamma2Inv) 0 0 =
      su2OfVec (R2 η) 0 0
    rw [mat2_triple_00]
    simp [gamma2, gamma2Inv, su2OfVec, R2] <;> ring
  · change (gamma2 * su2OfVec η * gamma2Inv) 0 1 =
      su2OfVec (R2 η) 0 1
    rw [mat2_triple_01]
    simp [gamma2, gamma2Inv, su2OfVec, R2] <;> ring
  · change (gamma2 * su2OfVec η * gamma2Inv) 1 0 =
      su2OfVec (R2 η) 1 0
    rw [mat2_triple_10]
    simp [gamma2, gamma2Inv, su2OfVec, R2] <;> ring
  · change (gamma2 * su2OfVec η * gamma2Inv) 1 1 =
      su2OfVec (R2 η) 1 1
    rw [mat2_triple_11]
    simp [gamma2, gamma2Inv, su2OfVec, R2] <;> ring

theorem gamma3_conj_su2 (η : Vec3) :
    gamma3 * su2OfVec η * gamma3Inv =
      su2OfVec (R3 η) := by
  funext i j
  fin_cases i <;> fin_cases j
  · change (gamma3 * su2OfVec η * gamma3Inv) 0 0 =
      su2OfVec (R3 η) 0 0
    rw [mat2_triple_00]
    simp [gamma3, gamma3Inv, su2OfVec, R3]
    rw [I_mul_mul_I]
    ring
  · change (gamma3 * su2OfVec η * gamma3Inv) 0 1 =
      su2OfVec (R3 η) 0 1
    rw [mat2_triple_01]
    simp [gamma3, gamma3Inv, su2OfVec, R3]
    rw [I_mul_mul_I]
    ring
  · change (gamma3 * su2OfVec η * gamma3Inv) 1 0 =
      su2OfVec (R3 η) 1 0
    rw [mat2_triple_10]
    simp [gamma3, gamma3Inv, su2OfVec, R3]
    rw [I_mul_mul_I]
    ring
  · change (gamma3 * su2OfVec η * gamma3Inv) 1 1 =
      su2OfVec (R3 η) 1 1
    rw [mat2_triple_11]
    simp [gamma3, gamma3Inv, su2OfVec, R3]
    rw [I_mul_mul_I]

theorem gamma4_conj_su2 (η : Vec3) :
    gamma4 * su2OfVec η * gamma4Inv =
      su2OfVec (R4 η) := by
  funext i j
  fin_cases i <;> fin_cases j
  · change (gamma4 * su2OfVec η * gamma4Inv) 0 0 = su2OfVec (R4 η) 0 0
    rw [mat2_triple_00]
    simp [gamma4, gamma4Inv, su2OfVec, R4]
  · change (gamma4 * su2OfVec η * gamma4Inv) 0 1 = su2OfVec (R4 η) 0 1
    rw [mat2_triple_01]
    simp [gamma4, gamma4Inv, su2OfVec, R4]
  · change (gamma4 * su2OfVec η * gamma4Inv) 1 0 = su2OfVec (R4 η) 1 0
    rw [mat2_triple_10]
    simp [gamma4, gamma4Inv, su2OfVec, R4]
  · change (gamma4 * su2OfVec η * gamma4Inv) 1 1 = su2OfVec (R4 η) 1 1
    rw [mat2_triple_11]
    simp [gamma4, gamma4Inv, su2OfVec, R4]

/-- Uniform twist-eater family. -/
def gamma : Fin 4 → Mat2C :=
  ![gamma1, gamma2, gamma3, gamma4]

/-- Uniform inverse family. -/
def gammaInv : Fin 4 → Mat2C :=
  ![gamma1Inv, gamma2Inv, gamma3Inv, gamma4Inv]

/-- Uniform coordinate adjoint rotation. -/
def twistRotation (μ : Fin 4) (η : Vec3) : Vec3 :=
  ![R1 η, R2 η, R3 η, R4 η] μ

/--
**Pauli/twist-eater bridge.**

Conjugation of `i η·σ` by the actual background matrix `Γμ`
is represented exactly by `twistRotation μ η`.
-/
theorem twistConjugation_su2 (μ : Fin 4) (η : Vec3) :
    gamma μ * su2OfVec η * gammaInv μ =
      su2OfVec (twistRotation μ η) := by
  fin_cases μ
  · exact gamma1_conj_su2 η
  · exact gamma2_conj_su2 η
  · exact gamma3_conj_su2 η
  · exact gamma4_conj_su2 η

#print axioms mat2_mul_00
#print axioms mat2_mul_01
#print axioms mat2_mul_10
#print axioms mat2_mul_11
#print axioms mat2_triple_00
#print axioms mat2_triple_01
#print axioms mat2_triple_10
#print axioms mat2_triple_11
#print axioms I_mul_mul_I
#print axioms I_mul_mul_negI
#print axioms negI_mul_mul_I
#print axioms negI_mul_mul_negI
#print axioms gamma1_eq_I_smul_sigma1
#print axioms gamma2_eq_I_smul_sigma2
#print axioms gamma3_eq_I_smul_sigma3
#print axioms gamma1_mul_gamma1Inv
#print axioms gamma2_mul_gamma2Inv
#print axioms gamma3_mul_gamma3Inv
#print axioms gamma4_mul_gamma4Inv
#print axioms gamma1_conj_su2
#print axioms gamma2_conj_su2
#print axioms gamma3_conj_su2
#print axioms gamma4_conj_su2
#print axioms twistConjugation_su2

end SU2
end YMFormalization
